#!/usr/bin/env python3
"""Download rss.chat's public feeds and write a local D1 seed fixture."""
from __future__ import annotations

import datetime
import email.utils
import html
import re
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "fixtures/rss-chat"
BASE = "https://rss.chat"
SOURCE_NS = "{https://source.scripting.com/}"


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"user-agent": "rss.voice fixture generator"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def text(node: ET.Element | None) -> str | None:
    if node is None or node.text is None:
        return None
    value = node.text.strip()
    return value or None


def sql(value: object | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def number(value: str | None) -> int | None:
    try:
        return int(value) if value is not None else None
    except ValueError:
        return None


def iso_date(value: str | None) -> str | None:
    if not value:
        return None
    parsed = email.utils.parsedate_to_datetime(value)
    return parsed.astimezone(datetime.timezone.utc).isoformat().replace("+00:00", "Z")


opml = ET.fromstring(fetch(f"{BASE}/data/subs.opml"))
users: dict[str, dict[str, str | None]] = {}
for outline in opml.findall(".//outline"):
    name = outline.get("text")
    if name:
        users[name] = {"feed_title": name, "feed_link": f"{BASE}/?name={name}", "feed_description": f"Posts by {name}", "avatar_url": None}

aggregate_bytes = fetch(f"{BASE}/users/rss.xml")
(OUT / "subs.opml").write_bytes(fetch(f"{BASE}/data/subs.opml"))
(OUT / "users.xml").write_bytes(aggregate_bytes)

# Channel metadata makes local personal feeds look like the reference feeds.
for name, metadata in users.items():
    try:
        channel = ET.fromstring(fetch(f"{BASE}/users/{urllib.parse.quote(name)}/rss.xml")).find("channel")
        if channel is not None:
            metadata["feed_title"] = text(channel.find("title")) or metadata["feed_title"]
            metadata["feed_link"] = text(channel.find("link")) or metadata["feed_link"]
            metadata["feed_description"] = text(channel.find("description")) or metadata["feed_description"]
            metadata["avatar_url"] = text(channel.find("image/url"))
    except Exception as error:  # one unavailable personal feed should not block the fixture
        print(f"warning: could not fetch {name}: {error}")

root = ET.fromstring(aggregate_bytes)
posts: list[dict[str, object | None]] = []
for item in root.findall("./channel/item"):
    source = item.find("source")
    feed_url = source.get("url", "") if source is not None else ""
    match = re.search(r"/users/([^/]+)/rss\.xml$", feed_url)
    author = urllib.parse.unquote(match.group(1)) if match else None
    if not author or author not in users:
        continue
    guid = text(item.find("guid"))
    post_id = number(re.search(r"[?&]id=(\d+)", guid or "").group(1)) if re.search(r"[?&]id=(\d+)", guid or "") else None
    if post_id is None:
        continue
    reply_url = text(item.find(f"{SOURCE_NS}inReplyTo"))
    reply_match = re.search(r"[?&]id=(\d+)", reply_url or "")
    enclosure = item.find("enclosure")
    posts.append({
        "id": post_id,
        "author": author,
        "title": text(item.find("title")),
        "description": text(item.find("description")),
        "markdowntext": text(item.find(f"{SOURCE_NS}markdown")),
        "link": text(item.find("link")),
        "reply": int(reply_match.group(1)) if reply_match else None,
        "enclosure_url": enclosure.get("url") if enclosure is not None else None,
        "enclosure_type": enclosure.get("type") if enclosure is not None else None,
        "enclosure_length": number(enclosure.get("length")) if enclosure is not None else None,
        "published_at": iso_date(text(item.find("pubDate"))),
    })

lines = [
    "-- Generated by scripts/fetch-rss-chat-fixture.py; public rss.chat data for local E2E tests.",
    "PRAGMA foreign_keys = ON;",
    "DELETE FROM likes WHERE tenant_id = 'default';",
    "DELETE FROM posts WHERE tenant_id = 'default';",
]
for name, metadata in users.items():
    values = ["default", name, name, metadata["feed_title"], metadata["feed_link"], metadata["feed_description"], metadata["avatar_url"]]
    lines.append("INSERT INTO users (tenant_id, screenname, display_name, feed_title, feed_link, feed_description, avatar_url) VALUES (" + ", ".join(sql(value) for value in values) + ") ON CONFLICT(tenant_id, screenname) DO UPDATE SET display_name=excluded.display_name, feed_title=excluded.feed_title, feed_link=excluded.feed_link, feed_description=excluded.feed_description, avatar_url=excluded.avatar_url;")
for post in posts:
    values = ["default", post["id"], post["author"], post["title"], post["description"], post["markdowntext"], post["link"], post["reply"], post["enclosure_url"], post["enclosure_type"], post["enclosure_length"], post["published_at"]]
    lines.append("INSERT OR IGNORE INTO posts (tenant_id, id, author, title, description, markdowntext, link, in_reply_to, enclosure_url, enclosure_type, enclosure_length, published_at, updated_at) VALUES (" + ", ".join(map(sql, values + [post["published_at"]])) + ");")

(OUT / "seed.sql").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(users)} users and {len(posts)} posts to {OUT / 'seed.sql'}")
